config/routes.rb
Rails.application.routes.draw do
  # Create
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  # Read
  get 'index', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show'
  # Update
  get 'tasks/:id/edit', to: 'tasks#edit'
  patch 'tasks/:id', to: 'tasks#update', as: 'task'
  # Delete
  delete 'tasks/:id', to: 'tasks#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # create
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to index_path
  end

  # read
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  # update
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to index_path
  end

  # delete
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to index_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
  <head>
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
  </head>
  <h1>Edit <em><%=@task.title%></em></h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed  %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<body>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
  </head>
  <h1>
    MY TASKS:
  </h1>
  <% @tasks.each do |tax| %>
<% if tax.completed %>
      <div>
        <input type="checkbox" name="task" checked>
        <label for="task"><%= link_to tax.title, "tasks/#{tax.id}" %></label>
        <%= link_to "Edit", "tasks/#{tax.id}/edit"  %>
        <%= link_to "🗑", "tasks/#{tax.id}", method: :delete, data: { confirm: "Are you sure?" } %>
       </div>
    <% else %>
      <div>
        <input type="checkbox" name="task">
        <label for="task"><%= link_to tax.title, "tasks/#{tax.id}" %></label>
        <%= link_to "Edit", "tasks/#{tax.id}/edit"  %>
        <%= link_to "🗑", "tasks/#{tax.id}", method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    <% end %>
<% end %>

<div>
  <%= link_to "Create a new task", tasks_new_path  %>
</div>


</body>

app/views/tasks/new.html.erb
  <head>
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
  </head>
<h1>New task</h1>
<%= form_for(@task) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :details %>
<%= f.text_field :details %>

<%= f.submit %>
<% end %>

<%= link_to "Create a new task", tasks_new_path  %>
<%= link_to "Back to the list", index_path %>

app/views/tasks/show.html.erb
  <head>
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
  </head>
<h1><%= @task.title  %></h1>
<p><%= @task.details  %></p>
<p>Status: <% if @task.completed %>
      <div>
        <input type="checkbox" name="task" checked>
        <label for="task">Task completed</label>
       </div>
    <% else %>
      <div>
        <label for="task">This task has not yet been completed</label>
      </div>
    <% end %>
</p>
<%= link_to "Return to list of tasks", index_path  %>